Adding command line example
witnet/vrf-rs pull request #20
Opened 2020-05-03 20:21 UTC by manfr3d

USAGE:
    cli [FLAGS] <SECRET_KEY> <MESSAGE> [PROOF]

2020-05-04 10:27 UTC, girazoki requested changes

2020-05-04 10:27 UTC, girazoki commented on examples/cli.rs
> +
```suggestion
```

2020-05-04 10:27 UTC, girazoki commented on examples/cli.rs
> +
```suggestion
```

2020-05-04 10:27 UTC, girazoki commented on examples/cli.rs
> +
```suggestion
```

2020-05-04 10:27 UTC, girazoki commented on examples/cli.rs
> +use vrf::openssl::{CipherSuite, ECVRF};
```suggestion
use hex;
use vrf::openssl::{CipherSuite, ECVRF};
```

2020-05-04 10:27 UTC, girazoki commented on examples/cli.rs
> +use hex;
```suggestion
```

2020-05-04 16:06 UTC, manfr3d commented
Changes accepted!

2020-05-04 16:15 UTC, girazoki commented on examples/cli.rs
> +
```suggestion
```

2020-05-05 12:31 UTC, manfr3d commented
Changes accepted.

2020-05-05 16:27 UTC, girazoki approved these changes

2020-05-05 16:29 UTC, girazoki commented
Hi @manfr3d and thanks for the contribution! Can you squash your commits into the latest one? We require to have a clean and verified history in the repo. Thanks in advance!

2020-05-05 16:48 UTC, manfr3d commented
That works is you neeed to remove the last commit? Thanks.

2020-05-06 07:19 UTC, girazoki commented
No, just join all the commits together into the latest

2020-05-06 14:32 UTC, manfr3d commented
Works now?

2020-05-06 15:38 UTC, girazoki commented
I squashed them for you @manfr3d. This PR is closed by 51fb9b78126280de443b5b5c33c3377788f0d702

2020-05-06 15:40 UTC, closed without merging