fix(ecvrf): add Debug impl to ECVRF struct
witnet/vrf-rs pull request #6
Opened 2019-05-17 15:36 UTC by mariocao

Add `Debug` implementation to `ECVRF` structure.

Some of the `openssl` fields, such as `BigNumContext`, `ECCurve` and `MessageDigest` do not implement `Debug`. However they are not really important as this information is already included in the field `cipher_suite`. :smile:

2019-05-17 20:37 UTC, aesedepece requested changes

2019-05-17 20:37 UTC, aesedepece commented on src/openssl/mod.rs
> +    /// The proof lengthCould provide an issue description? is invalid
This does probably not belong here.

2019-05-17 20:37 UTC, aesedepece commented on src/openssl/mod.rs
> +impl Debug for ECVRF {
I support this implementation for the sake of not adding more dependencies to this library.

For what it's worth, there are a couple of crates providing macros that achieve the same goal of excluding some fields from the `struct` so the `Debug` implementation can be automatically `Derive`d:
- [debug_stub_derive](https://crates.io/crates/debug_stub_derive)
- [derivative](https://crates.io/crates/derivative)

2019-05-20 13:01 UTC, tmpolaczyk approved these changes
Looks good to me

2019-05-20 14:38 UTC, aesedepece approved these changes

2019-05-22 09:35 UTC, merged